# Generated by Django 4.2.7 on 2023-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_slug_category_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('descriprion', models.TextField()),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
